task_manager/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from task_manager import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='main'),
    path('users/', include('users.urls')),
    path('labels/', include('labels.urls')),
    path('statuses/', include('statuses.urls')),
    path('tasks/', include('tasks.urls')),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

]

tasks/urls.py
from django.urls import path
from tasks import views


app_name = 'tasks'
urlpatterns = [
    path('', views.TasksView.as_view(template_name='tasks.html'), name='tasks'),
    path('create/', views.CreateTask.as_view(), name='create'),
    path('<int:pk>/', views.TaskDetailView.as_view(), name='view_task'),
    path('<int:pk>/update/', views.UpdateTask.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteTask.as_view(), name='delete'),

]

tasks/models.py
from django.db import models
from users.models import User
from statuses.models import Status
from labels.models import Labels
from django.utils.translation import gettext as _


class Task(models.Model):
    name = models.CharField(max_length=100, verbose_name=_('Name'))
    status = models.ForeignKey(Status, null=True, on_delete=models.PROTECT, verbose_name=_('Status'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('Date joined'))
    description = models.TextField(blank=True, null=True)
    author = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='authored_tasks',
        verbose_name=_('Author'),)
    executor = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='tasks_assigned_to',
        verbose_name=_('Executor'),)
    labels = models.ManyToManyField(
        Labels,
        blank=True,
        verbose_name=_('Labels'),)

    def __str__(self):
        return self.name

tasks/forms.py
from django import forms
from tasks.models import Task


class TaskForm(forms.ModelForm):

    class Meta():
        model = Task
        fields = ('name', 'description', 'status', 'executor', 'labels')

tasks/views.py
from tasks.models import Task
from tasks.forms import TaskForm
from tasks.tables import TaskTable
from tasks.filter import TaskFilter
from django.contrib import messages
from django.urls.base import reverse_lazy
from django_tables2 import SingleTableView
from django_filters.views import FilterView
from django.utils.translation import gettext as _
from django.views.generic import DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import UpdateView, DeleteView


class TasksView(LoginRequiredMixin, FilterView, SingleTableView):
    model = Task
    filterset_class = TaskFilter
    table_class = TaskTable
    extra_context = {'title': _('Tasks')}


class TaskDetailView(LoginRequiredMixin, DetailView):
    model = Task
    template_name = 'task_view.html'
    extra_context = {'title': _('Task view')}


class CreateTask(LoginRequiredMixin, CreateView):
    model = Task
    template_name = 'general_pattern.html'
    form_class = TaskForm
    success_url = reverse_lazy('tasks:tasks')
    extra_context = {'title': _('Tasks')}

    def form_valid(self, form):
        form.instance.author = self.request.user
        messages.success(self.request, _('Task created successfully'))
        return super().form_valid(form)


class UpdateTask(LoginRequiredMixin, UpdateView):
    model = Task
    template_name = 'general_pattern.html'
    extra_context = {'title': _('Changing task')}
    form_class = TaskForm
    success_url = reverse_lazy('tasks:tasks')

    def form_valid(self, form):
        messages.success(self.request, _('Task updated'))
        return super().form_valid(form)


class DeleteTask(LoginRequiredMixin, DeleteView):
    model = Task
    template_name = "delete.html"
    extra_context = {'title': _('Delete task')}
    success_url = reverse_lazy('tasks:tasks')

    def form_valid(self, form):
        if self.request.user == self.get_object().author:
            messages.success(self.request, _('Task deleted successfully'))
            return super().form_valid(form)
        else:
            form.add_error(None, _('Task can be deleted only by the owner'))
            return self.form_invalid(form)

tasks/templates/task_view.html
{% extends 'base.html' %}
{% load i18n %}
{% load bootstrap4 %}
{% bootstrap_css %}

  
{% block content %}
<div class="container wrapper flex-grow-1">
    <h1 class="my-4">{% translate title %}</h1>
    <div class="card">
        <div class="card-header bg-secondary text-white">
            <h2>{{ task.name }}</h2>
        </div>

        <div class="card-body bg-light">
            <p>{{ task.description }}</p>
            <hr>
            <div class="container">
                <div class="row p-1">  
                    <div class="col">{% translate "Author" %}</div>
                    <div class="col">{{ task.author }}</div>
                </div>
                <div class="row p-1">  
                    <div class="col">{% translate "Executor" %}</div>
                    <div class="col">{{ task.executor }}</div>
                </div>
                <div class="row p-1">  
                    <div class="col">{% translate "Status" %}</div>
                    <div class="col">{{ task.status }}</div>
                </div>
                <div class="row p-1">  
                    <div class="col">{% translate "Created date" %}</div>
                    <div class="col">{{ task.created_at }}</div>
                </div>
                <div class="row p-1">  
                    <div class="col"><h6>{% translate "Labels" %}:</h6>
                        <ul>
                            {% for label in task.labels.all %}
                                <li>{{ label.name }}</li>
                          {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="row p-1">
                    <div class="col">
                      <a href="{% url 'tasks:update' task.pk %}">{% translate 'Edit' %}</a>
                      <br>
                      <a href="{% url 'tasks:delete' task.pk %}">{% translate 'Delete' %}</a>
                    </div>
                </div>
            </div>
        </div>
    </div>     
</div>

{% endblock content %}

tasks/templates/tasks.html
{% extends 'base.html' %}
{% load i18n %}
{% load render_table from django_tables2 %}
{% load bootstrap4 %}
{% bootstrap_css %}

  
{% block content %}

<div class="container wrapper flex-grow-1">
    <h1 class="my-4">{% translate title %}</h1>
    <a class="nav-link" href="{% url 'tasks:create' %}">{% translate 'Create Task' %}</a>
    
    <div class="card mb-3">
        <div class="card-body bg-light">
            <form class="form-inline" method="get">
                {% csrf_token %}
                {% for field in filter.form %}
                    {% bootstrap_field field field_class='ml-2 mr-3'%}
                {% endfor %}
                <button type="submit" class="btn btn-primary ml-3">{% translate "Filter" %}</button>
            </form>
        </div>
    </div>     
            
    {% for task in filter.qs %}
        <div>{{ task.title }}</div>
    {% empty %}
        <div> No tasks found. </div>
        <hr>
    {% endfor %}
            
    {% render_table table %}
</div>
{% endblock content %}