labels/urls.py
from django.urls import path
from labels import views


app_name = 'labels'
urlpatterns = [
    path('', views.LabelsView.as_view(template_name='labels_statuses.html'), name='labels'),  # noqa:E501
    path('create/', views.CreateLabel.as_view(), name='create'),
    path('<int:pk>/update/', views.UpdateLabel.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteLabel.as_view(), name='delete'),

]

statuses/urls.py
from django.urls import path
from statuses import views


app_name = 'statuses'
urlpatterns = [
    path('', views.StatusesView.as_view(template_name='labels_statuses.html'), name='statuses'),
    path('create/', views.CreateStatus.as_view(), name='create'),
    path('<int:pk>/update/', views.UpdateStatus.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteStatus.as_view(), name='delete'),

]

task_manager/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from task_manager import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='main'),
    path('users/', include('users.urls')),
    path('labels/', include('labels.urls')),
    path('statuses/', include('statuses.urls')),
    path('tasks/', include('tasks.urls')),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

]

tasks/urls.py
from django.urls import path
from tasks import views


app_name = 'tasks'
urlpatterns = [
    path('', views.TasksView.as_view(template_name='tasks.html'), name='tasks'),
    path('create/', views.CreateTask.as_view(), name='create'),
    path('<int:pk>/', views.TaskDetailView.as_view(), name='view_task'),
    path('<int:pk>/update/', views.UpdateTask.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteTask.as_view(), name='delete'),

]

labels/models.py
from django.db import models
from django.utils.translation import gettext as _


class Labels(models.Model):
    name = models.CharField(max_length=100, verbose_name=_('Name'))
    created_at = models.DateTimeField(auto_now_add=True,
                                      verbose_name=_('Created date'))

    def __str__(self):
        return self.name

labels/forms.py
from django import forms
from labels.models import Labels


class LabelForm(forms.ModelForm):

    class Meta():
        model = Labels
        fields = ('name',)

labels/views.py
from .forms import LabelForm
from .tables import LabelsTable
from labels.models import Labels
from django.views import generic
from django.contrib import messages
from django.urls.base import reverse_lazy
from django_tables2 import SingleTableView
from django.utils.translation import gettext as _
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import UpdateView, DeleteView


class LabelsView(LoginRequiredMixin, SingleTableView):
    model = Labels
    template_name = 'templates/labels_statuses.html'
    table_class = LabelsTable
    extra_context = {'title': _('Labels'), 'page_type': 'labels'}


class CreateLabel(LoginRequiredMixin, generic.CreateView):
    model = Labels
    template_name = 'general_pattern.html'
    form_class = LabelForm
    success_url = reverse_lazy('labels:labels')
    extra_context = {'title': _('Create label'), }

    def form_valid(self, form):
        messages.success(self.request, _('Label created successfully'))
        return super().form_valid(form)


class UpdateLabel(LoginRequiredMixin, UpdateView):
    model = Labels
    template_name = 'general_pattern.html'
    extra_context = {'title': _('Label change')}
    form_class = LabelForm
    success_url = reverse_lazy('labels:labels')

    def form_valid(self, form):
        messages.success(self.request, _('Label updated'))
        return super().form_valid(form)


class DeleteLabel(LoginRequiredMixin, DeleteView):
    model = Labels
    template_name = "delete.html"
    extra_context = {'title': _('Delete label')}
    success_url = reverse_lazy('labels:labels')

    def form_valid(self, form):
        messages.success(self.request, _('Label deleted successfully'))
        return super().form_valid(form)

labels/templates/labels-statuses-template.html
{% extends 'base.html' %}
{% load i18n %}
{% load render_table from django_tables2 %}
{% load bootstrap4 %}
{% bootstrap_css %}

{% block content %}

<div class="container wrapper flex-grow-1">
    <h1 class="my-4">{% translate title %}</h1>
        {% if page_type == 'labels' %}
            <a class="nav-link" href="{% url 'labels:create' %}">{% translate 'Create Label' %}</a>
        {% elif page_type == 'statuses' %}
            <a class="nav-link" href="{% url 'statuses:create' %}">{% translate 'Create Status' %}</a>
        {% endif %}
    {% render_table table %}
</div>

{% endblock %}

labels/templates/labels_statuses.html
{% extends 'base.html' %}

{% load i18n %}

{% load render_table from django_tables2 %}
{% load bootstrap4 %}

{% block content %}

<div class="container wrapper flex-grow-1">
    <h1 class="my-4">{% translate title %}</h1>
        {% if page_type == 'labels' %}
            <a class="nav-link" href="{% url 'labels:create' %}">{% translate 'Create Label' %}</a>
        {% elif page_type == 'statuses' %}
            <a class="nav-link" href="{% url 'statuses:create' %}">{% translate 'Create Status' %}</a>
        {% endif %}
    {% render_table table %}
</div>

{% endblock %}