labels/urls.py
from django.urls import path
from labels import views


app_name = 'labels'
urlpatterns = [
    path('', views.LabelsView.as_view(template_name='labels_statuses.html'), name='labels'),  # noqa:E501
    path('create/', views.CreateLabel.as_view(), name='create'),
    path('<int:pk>/update/', views.UpdateLabel.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteLabel.as_view(), name='delete'),

]

statuses/urls.py
from django.urls import path
from statuses import views


app_name = 'statuses'
urlpatterns = [
    path('', views.StatusesView.as_view(template_name='labels_statuses.html'), name='statuses'),
    path('create/', views.CreateStatus.as_view(), name='create'),
    path('<int:pk>/update/', views.UpdateStatus.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteStatus.as_view(), name='delete'),

]

task_manager/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from task_manager import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='main'),
    path('users/', include('users.urls')),
    path('labels/', include('labels.urls')),
    path('statuses/', include('statuses.urls')),
    path('tasks/', include('tasks.urls')),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

]

tasks/urls.py
from django.urls import path
from tasks import views


app_name = 'tasks'
urlpatterns = [
    path('', views.TasksView.as_view(template_name='tasks.html'), name='tasks'),
    path('create/', views.CreateTask.as_view(), name='create'),
    path('<int:pk>/', views.TaskDetailView.as_view(), name='view_task'),
    path('<int:pk>/update/', views.UpdateTask.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteTask.as_view(), name='delete'),

]

users/urls.py
from django.urls import path
from users import views


app_name = 'users'
urlpatterns = [
    path('', views.UserView.as_view(template_name='users.html'), name='users'),
    path('create/', views.CreateUser.as_view(), name='create'),
    path('<int:pk>/update/', views.UpdateUser.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteUser.as_view(), name='delete'),

]

task_manager/views.py
from django.views import View
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.utils.translation import gettext as _
from django.contrib.auth.forms import AuthenticationForm


def index(request):
    return render(request, 'index.html',)


class LoginView(View):
    template_name = 'general_pattern.html'
    extra_context = {'title': _('Entrance')}

    def get(self, request, *args, **kwargs):
        form = AuthenticationForm()
        return render(request, self.template_name,
                      {'form': form, **self.extra_context})

    def post(self, request, *args, **kwargs):
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            messages.success(request, _('You have successfully logged in'))
            return redirect('main')
        return render(request, self.template_name, {'form': form})


class LogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        messages.info(request, _('You are logged out'))
        return redirect('main')

task_manager/templates/base.html
<!doctype html>

{% load i18n %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}


<html lang="ru-ru">

    <meta charset="utf-8">
  <head>
      <title>
        {% block title %}
          {% translate 'Task manager' %}
        {% endblock %}
      </title>
  </head>
  
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'main' %}">{% translate 'Task manager' %}</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:users' %}">{% translate 'Users' %}</a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'statuses:statuses' %}">{% translate 'Statuses' %}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'labels:labels' %}">{% translate 'Labels' %}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'tasks:tasks' %}">{% translate 'Tasks' %}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">{% translate 'Logout' %}</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">{% translate 'Entrance' %}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:create' %}">{% translate 'Registration' %}</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <div class="container wrapper flex-grow-1">
      {% bootstrap_messages %}
    </div>

    <div id="content">
      {% block content %}{% endblock %}
    </div>
    <footer>
      <div class="container my-5 pt-4 border-top">
        <a target="_blank" href="https://github.com/kat-git-hub">BlaBla</a>
      </div>
    </footer>
  </body>
</html>

task_manager/templates/index.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load i18n %}
{% bootstrap_css %}

{% block content %}
<div class="container wrapper flex-grow-1">
    <div class="card">
        <div class="card-body p-5 bg-light">
        <h1>{% translate 'Hello!' %}</h1>
        <p class="lead">{% translate 'This is my task manager created on Django.' %}</p>
        <a class="btn btn-lg btn-primary" href="https://github.com/kat-git-hub" role="button">{% translate 'Learn more' %} &raquo;</a>
        </div>
    </div>
</div>
{% endblock content %}